FROM node:16-alpine
WORKDIR /melbeez-admintool
ENV PATH="/melbeez-admintool/node_modules/.bin:$PATH"
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY .env.production ./
COPY . .
RUN npm run build
EXPOSE 5000
CMD ["npx", "serve", "-s", "build"]












