import { headerSortingClasses } from "../../../_metronic/_helpers";
import renderActions from "./RenderAction";
const warrantyData = [
    {
        id: 1,
        manufacturerName1: "ako",
        warrantyId: "12345",
        monthlyPrice: "$100",
        annualPrice: "$1000",
        melbeezDiscount: "10%",
        uploadPicture: "Upload Picture 1",
        created: "2024-05-20",
        updated: "2024-05-21",
        lastUpdated: "2024-05-21",
        status: "Pending",
        product: "Product 1",
    },
    {
        id: 2,
        manufacturerName1: "ako",
        warrantyId: "12398",
        monthlyPrice: "$150",
        annualPrice: "$1500",
        melbeezDiscount: "15%",
        uploadPicture: "Upload Picture 2",
        created: "2024-05-20",
        updated: "2024-05-21",
        lastUpdated: "2024-05-21",
        status: "Approved",
        product: "Product 2",
    },
    {
        id: 3,
        manufacturerName1: "bko",
        warrantyId: "12346",
        monthlyPrice: "$110",
        annualPrice: "$1100",
        melbeezDiscount: "11%",
        uploadPicture: "Upload Picture 3",
        created: "2024-05-21",
        updated: "2024-05-22",
        lastUpdated: "2024-05-22",
        status: "Submitted",
        product: "Product 3",
    },
    {
        id: 4,
        manufacturerName1: "cko",
        warrantyId: "12347",
        monthlyPrice: "$120",
        annualPrice: "$1200",
        melbeezDiscount: "12%",
        uploadPicture: "Upload Picture 4",
        created: "2024-05-22",
        updated: "2024-05-23",
        lastUpdated: "2024-05-23",
        status: "Rejected",
        product: "Product 4",
    },
    {
        id: 5,
        manufacturerName1: "dko",
        warrantyId: "12348",
        monthlyPrice: "$130",
        annualPrice: "$1300",
        melbeezDiscount: "13%",
        uploadPicture: "Upload Picture 5",
        created: "2024-05-23",
        updated: "2024-05-24",
        lastUpdated: "2024-05-24",
        status: "Pending",
        product: "Product 5",
    },
    {
        id: 6,
        manufacturerName1: "eko",
        warrantyId: "12349",
        monthlyPrice: "$140",
        annualPrice: "$1400",
        melbeezDiscount: "14%",
        uploadPicture: "Upload Picture 6",
        created: "2024-05-24",
        updated: "2024-05-25",
        lastUpdated: "2024-05-25",
        status: "Approved",
        product: "Product 6",
    },
    {
        id: 7,
        manufacturerName1: "fko",
        warrantyId: "12350",
        monthlyPrice: "$160",
        annualPrice: "$1600",
        melbeezDiscount: "16%",
        uploadPicture: "Upload Picture 7",
        created: "2024-05-25",
        updated: "2024-05-26",
        lastUpdated: "2024-05-26",
        status: "Submitted",
        product: "Product 7",
    },
    {
        id: 8,
        manufacturerName1: "gko",
        warrantyId: "12351",
        monthlyPrice: "$170",
        annualPrice: "$1700",
        melbeezDiscount: "17%",
        uploadPicture: "Upload Picture 8",
        created: "2024-05-26",
        updated: "2024-05-27",
        lastUpdated: "2024-05-27",
        status: "Rejected",
        product: "Product 8",
    },
    {
        id: 9,
        manufacturerName1: "hko",
        warrantyId: "12352",
        monthlyPrice: "$180",
        annualPrice: "$1800",
        melbeezDiscount: "18%",
        uploadPicture: "Upload Picture 9",
        created: "2024-05-27",
        updated: "2024-05-28",
        lastUpdated: "2024-05-28",
        status: "Pending",
        product: "Product 9",
    },
    {
        id: 10,
        manufacturerName1: "iko",
        warrantyId: "12353",
        monthlyPrice: "$190",
        annualPrice: "$1900",
        melbeezDiscount: "19%",
        uploadPicture: "Upload Picture 10",
        created: "2024-05-28",
        updated: "2024-05-29",
        lastUpdated: "2024-05-29",
        status: "Approved",
        product: "Product 10",
    },
];

const columns = [
    {
        dataField: "manufacturerName1",
        text: "Ven",
        headerSortingClasses,
    },
    {
        dataField: "warrantyId",
        text: "Warra",
        headerSortingClasses,
    },
    {
        dataField: "product",
        text: "Name",
        headerSortingClasses,
    },
    {
        dataField: "monthlyPrice",
        text: "Monthly",
        headerSortingClasses,
    },
    {
        dataField: "annualPrice",
        text: "Annual",
        headerSortingClasses,
    },
    {
        dataField: "melbeezDiscount",
        text: "Melbeez",
        headerSortingClasses,
    },
    {
        dataField: "product",
        text: "Product",
        headerSortingClasses,
    },
    {
        dataField: "product",
        text: "Terms & C",
        headerSortingClasses,
    },
    {
        dataField: "created",
        text: "Created",
        headerSortingClasses,
    },
    {
        dataField: "updated",
        text: "Updated",
        headerSortingClasses,
    },
    {
        dataField: "lastUpdated",
        text: "LastUpdated",
        headerSortingClasses,
    },
    {
        dataField: "status",
        text: "Status",
        headerSortingClasses,
    },
    {
        dataField: "actions",
        text: "Actions",
        formatter: renderActions,
        classes: "text-center pr-0",
        headerClasses: "text-center pr-3",
        style: {
            minWidth: "100px",
        },
    },
];

export { warrantyData, columns };
